# Use an official Node runtime as a parent image
FROM node:latest

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in package.json
RUN npm install

# Make port 1234 available to the world outside this container
EXPOSE 1235

# Define environment variable
ENV NODE_ENV production

# Run your server file when the container launches
CMD ["node", "main.js"]
