apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: api-service
  spec:
    selector:
      app: api
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 9797

- apiVersion: v1
  kind: Service
  metadata:
    name: socket-service
  spec:
    selector:
      app: socket
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 1234
