
# Use Node.js 14 as the base image
FROM node:14

# Create a directory for the app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the app source code to the container
COPY . .

# Expose the ports used by the app
EXPOSE 1234
EXPOSE 9797

# Start the app
CMD [ "npm", "start" ]
